[font]
size = 14.0

[font.normal]
family = "FiraCode"
style = "Regular"

[window]
opacity = 0.80

[window.padding]
x = 5
y = 0

[selection]
save_to_clipboard = true

[cursor]

[general]
import = ["~/.config/alacritty/dank-theme.toml"]

[[keyboard.bindings]]
key = "Return"
mods = "Shift"
chars = "\u001B\r"
