---
- name: Clone dotfiles repository
  ansible.builtin.git:
    repo: "{{ dotfiles_repo }}"
    dest: "{{ dotfiles_dest }}"
    version: main
    update: false
  become: false

- name: Ensure ~/.config directory exists
  ansible.builtin.file:
    path: "{{ ansible_facts.env.HOME }}/.config"
    state: directory
    mode: "0755"
  become: false

- name: Stow dotfile packages
  ansible.builtin.command:
    cmd: "stow --dir={{ dotfiles_dest }} --target={{ ansible_facts.env.HOME }} --verbose=2 --adopt -R {{ item }}"
  loop: "{{ stow_packages }}"
  become: false
  register: stow_result
  changed_when: "'LINK: ' in stow_result.stderr"
